### ISSUE TITLE
Sorting of submissions in submission wall

### ISSUE THREAD

**Issue by tsauvine** [tsauvine/rubyric#50]
In the submission wall, the submissions should be sorted in a more clever way.

At the top, there should be a few submission with lots of comments so that users get an idea of what they are supposed to be doing. Also at the top, there should be a few of those submissions that we want to be reviewed next, i.e. the ones with the least reviews.

In practice, we could sort the submission by comment count, put ~2 of the most commented ones at the top, and the rest so that the most commented ones are at the bottom. There could be some randomization so that all submissions receive attention evenly.

Pay attention to performance. We can assume that there are a few hundred submissions and each has a few comments. If necessary, we can use pagination or lazy loading and randomize the order so that the same submissions are not always on page 2.

**Comment by nlhkh** [comment]
- Top:
  - Lots of comments: so that users get an idea of what they are supposed to be doing.
  - Least reviews: there should be a few of those submissions that we want to be reviewed next.

- In practice:
  - Sort submissions by comment count: put ~2 of the most commented ones at the top, and the rest at the bottom.
  - Randomization: so that all submissions receive attention evenly.

- Performance:
  - There are a few hundred submissions, each with a few comments.
  - If necessary:
    - Pagination
    - Lazy loading & randomizing the order so that the same submissions are not always on page 2.

**Comment by nlhkh** [comment]
Proposal:
  1. Sort submissions by comment count ASC (ascending)
  2. Pluck the last 2 submissions (with the most comments)
  3. Shuffle the rest
  4. Append the 2 submissions with the most comments with the shuffled list of submissions

Array functions:
  - Sort
  - Slice
  - Shuffle
  - Merge

```ruby
a = [ { x: 7 }, { x: 6 }, { x: 5 }, { x: 4 }, { x: 3 }, { x: 2 }, { x: 1 } ]

# Sort
a_sorted = a.sort { |a1, a2| a1[:x} <=> a2[:x] }

# Pluck last two
a_top = a[-2, -1]
a_rest = a[0..-3]

# Shuffle
a_shuffled = a_rest.shuffle

# Merge
a_new = a_top + a_shuffled
```

**Comment by nlhkh** [comment]
Pagination with randomization can be tricky, because the web is stateless. It would require prior knowledge of the 1st page to render a reasonable 2nd page.
- Perhaps we should not use randomization (or shuffling). We may instead have a deterministic way of sorting, e.g. submissions with least comments goes on top without randomization
- Use caching, even if you cache for 1 second, and suppose that you have 10000 concurrent requests in an instant, you reduce database access rate from 10000 to 1 (with the benefit that subsequence requests are served faster). 1 second is enough for the app to react to any changes.

**Comment by nlhkh** [comment]
@tsauvine There is a problem. The submissions are aggregated into groups. Do you want to sort the submissions across relevant groups?

**Comment by tsauvine** [comment]
I think we should shuffle, otherwise some submissions receive more attention than others. However, we should only shuffle the ones with an equal number of comments (there are a lot with 0 or 1). In other words, first shuffle, then sort by a stable method.

Caching is fine. In that case, we can invalidate the cache, let's say, once per hour and do the shuffling again.

Submissions of a group must always stay together. We should actually be talking about sorting groups instead of sorting submissions. The submissions within a group are always sorted by timestamp, and we are mostly interested in the latest one (the other submissions are usually just old versions). The comment count can be calculated from all submissions of the group.

**Comment by nlhkh** [comment]
Could you elaborate "first shuffle, then sort by a stable method"?

The way I understood your comment is that we aggregate the groups based on their total number of comments, and then we shuffle each aggregation, but I am not sure.

**Comment by tsauvine** [comment]
This would effectively shuffle the items with ties (the same number of comments). Something along these lines:
a = [ { x: 2 }, { x: 2 }, { x: 2 }, { x: 1 }, { x: 1 }, { x: 1 }, { x: 1 } ]
a_sorted = a.shuffle.stable_sort { |a1, a2| a1[:x] <=> a2[:x] }

The default Array#sort method is not stable and cannot be used in this case. However, it can be made stable:
https://8thlight.com/blog/will-warner/2013/03/26/stable-sorting-in-ruby.html

**Comment by tsauvine** [comment]
Actually, there's no harm in using an unstable sort because we want a random order anyway.

**Comment by nlhkh** [comment]
Got it!

1. Shuffle the groups
2. Sort groups by comment count for a given exercise

The goal is for the ones with least comments to be on top, with some randomization.

Do you still want to put 2 groups with the most comments on top?

**Comment by nlhkh** [comment]
Pending review

**Comment by nlhkh** [comment]
done
